import SyncsTable from '@/components/logs/SyncsTable';
import { useSyncs } from '@/hooks/useSyncs';
import Header from '@/layout/Header';
import { getServerSideProps } from '@/pages/applications/[applicationId]';
import { Box } from '@mui/material';
import Head from 'next/head';
import { useState } from 'react';

export { getServerSideProps };

export default function Home() {
  const [currentCursor, setCurrentCursor] = useState<string | undefined>(undefined);
  const { syncs, isLoading, mutate } = useSyncs(currentCursor);
  const [mobileOpen, setMobileOpen] = useState(false);

  const handleDrawerToggle = () => {
    setMobileOpen(!mobileOpen);
  };

  const handleNextPage = () => {
    if (syncs?.next) {
      setCurrentCursor(syncs.next);
    }
  };

  const handlePreviousPage = () => {
    if (syncs?.previous) {
      setCurrentCursor(syncs.previous);
    }
  };

  return (
    <>
      <Head>
        <title>Supaglue Management Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
        <Header title="Syncs" onDrawerToggle={handleDrawerToggle} />
        <Box component="main" sx={{ flex: 1, py: 6, px: 4, bgcolor: '#eaeff1' }}>
          <SyncsTable
            handleNextPage={handleNextPage}
            handlePreviousPage={handlePreviousPage}
            rowCount={syncs?.totalCount ?? 0}
            data={syncs?.results ?? []}
            isLoading={isLoading}
            mutate={mutate}
          />
        </Box>
      </Box>
    </>
  );
}
