# coding: utf-8

"""
    Supaglue CRM API

    # Introduction  Welcome to the Supaglue unified CRM API documentation. You can use this API to read data that has been synced into Supaglue from third-party providers.  ### Base API URL  ``` http://localhost:8080/crm/v1 ```   # noqa: E501

    OpenAPI spec version: 0.6.0
    Contact: docs@supaglue.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2005(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'url': 'str',
        'status': 'float',
        'headers': 'dict(str, str)',
        'body': 'AnyOfinlineResponse2005Body'
    }

    attribute_map = {
        'url': 'url',
        'status': 'status',
        'headers': 'headers',
        'body': 'body'
    }

    def __init__(self, url=None, status=None, headers=None, body=None):  # noqa: E501
        """InlineResponse2005 - a model defined in Swagger"""  # noqa: E501
        self._url = None
        self._status = None
        self._headers = None
        self._body = None
        self.discriminator = None
        self.url = url
        self.status = status
        self.headers = headers
        if body is not None:
            self.body = body

    @property
    def url(self):
        """Gets the url of this InlineResponse2005.  # noqa: E501

        The full URL the request was went to  # noqa: E501

        :return: The url of this InlineResponse2005.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this InlineResponse2005.

        The full URL the request was went to  # noqa: E501

        :param url: The url of this InlineResponse2005.  # noqa: E501
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def status(self):
        """Gets the status of this InlineResponse2005.  # noqa: E501

        Status code from the downstream  # noqa: E501

        :return: The status of this InlineResponse2005.  # noqa: E501
        :rtype: float
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse2005.

        Status code from the downstream  # noqa: E501

        :param status: The status of this InlineResponse2005.  # noqa: E501
        :type: float
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def headers(self):
        """Gets the headers of this InlineResponse2005.  # noqa: E501

        The response headers from the downstream  # noqa: E501

        :return: The headers of this InlineResponse2005.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._headers

    @headers.setter
    def headers(self, headers):
        """Sets the headers of this InlineResponse2005.

        The response headers from the downstream  # noqa: E501

        :param headers: The headers of this InlineResponse2005.  # noqa: E501
        :type: dict(str, str)
        """
        if headers is None:
            raise ValueError("Invalid value for `headers`, must not be `None`")  # noqa: E501

        self._headers = headers

    @property
    def body(self):
        """Gets the body of this InlineResponse2005.  # noqa: E501

        The body from the downstream  # noqa: E501

        :return: The body of this InlineResponse2005.  # noqa: E501
        :rtype: AnyOfinlineResponse2005Body
        """
        return self._body

    @body.setter
    def body(self, body):
        """Sets the body of this InlineResponse2005.

        The body from the downstream  # noqa: E501

        :param body: The body of this InlineResponse2005.  # noqa: E501
        :type: AnyOfinlineResponse2005Body
        """

        self._body = body

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2005, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2005):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
