# coding: utf-8

"""
    Supaglue CRM API

    # Introduction  Welcome to the Supaglue unified CRM API documentation. You can use this API to read data that has been synced into Supaglue from third-party providers.  ### Base API URL  ``` http://localhost:8080/api/crm/v1 ```   # noqa: E501

    OpenAPI spec version: 0.3.3
    Contact: docs@supaglue.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2005(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'model_name': 'str',
        'last_sync_start': 'str',
        'next_sync_start': 'str',
        'status': 'str'
    }

    attribute_map = {
        'model_name': 'model_name',
        'last_sync_start': 'last_sync_start',
        'next_sync_start': 'next_sync_start',
        'status': 'status'
    }

    def __init__(self, model_name=None, last_sync_start=None, next_sync_start=None, status=None):  # noqa: E501
        """InlineResponse2005 - a model defined in Swagger"""  # noqa: E501
        self._model_name = None
        self._last_sync_start = None
        self._next_sync_start = None
        self._status = None
        self.discriminator = None
        if model_name is not None:
            self.model_name = model_name
        if last_sync_start is not None:
            self.last_sync_start = last_sync_start
        if next_sync_start is not None:
            self.next_sync_start = next_sync_start
        if status is not None:
            self.status = status

    @property
    def model_name(self):
        """Gets the model_name of this InlineResponse2005.  # noqa: E501


        :return: The model_name of this InlineResponse2005.  # noqa: E501
        :rtype: str
        """
        return self._model_name

    @model_name.setter
    def model_name(self, model_name):
        """Sets the model_name of this InlineResponse2005.


        :param model_name: The model_name of this InlineResponse2005.  # noqa: E501
        :type: str
        """

        self._model_name = model_name

    @property
    def last_sync_start(self):
        """Gets the last_sync_start of this InlineResponse2005.  # noqa: E501


        :return: The last_sync_start of this InlineResponse2005.  # noqa: E501
        :rtype: str
        """
        return self._last_sync_start

    @last_sync_start.setter
    def last_sync_start(self, last_sync_start):
        """Sets the last_sync_start of this InlineResponse2005.


        :param last_sync_start: The last_sync_start of this InlineResponse2005.  # noqa: E501
        :type: str
        """

        self._last_sync_start = last_sync_start

    @property
    def next_sync_start(self):
        """Gets the next_sync_start of this InlineResponse2005.  # noqa: E501


        :return: The next_sync_start of this InlineResponse2005.  # noqa: E501
        :rtype: str
        """
        return self._next_sync_start

    @next_sync_start.setter
    def next_sync_start(self, next_sync_start):
        """Sets the next_sync_start of this InlineResponse2005.


        :param next_sync_start: The next_sync_start of this InlineResponse2005.  # noqa: E501
        :type: str
        """

        self._next_sync_start = next_sync_start

    @property
    def status(self):
        """Gets the status of this InlineResponse2005.  # noqa: E501


        :return: The status of this InlineResponse2005.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse2005.


        :param status: The status of this InlineResponse2005.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2005, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2005):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
