import { temporal } from '@temporalio/proto';

const { IndexedValueType } = temporal.api.enums.v1;

export const TEMPORAL_CUSTOM_SEARCH_ATTRIBUTES = {
  SYNC_ID: 'SyncId',
  APPLICATION_ID: 'ApplicationId',
  CUSTOMER_ID: 'CustomerId',
  INTEGRATION_ID: 'IntegrationId',
  PROVIDER_ID: 'ProviderId',
  SYNC_CONFIG_ID: 'SyncConfigId',
  CONNECTION_ID: 'ConnectionId',
  PROVIDER_CATEGORY: 'ProviderCategory',
  PROVIDER_NAME: 'ProviderName',
};

export const TEMPORAL_CONTEXT_ARGS = {
  SYNC_ID: 'syncId',
  APPLICATION_ID: 'applicationId',
  CUSTOMER_ID: 'customerId',
  INTEGRATION_ID: 'integrationId',
  PROVIDER_ID: 'providerId',
  SYNC_CONFIG_ID: 'syncConfigId',
  CONNECTION_ID: 'connectionId',
  PROVIDER_CATEGORY: 'providerCategory',
  PROVIDER_NAME: 'providerName',
};

export const TEMPORAL_CUSTOM_SEARCH_ATTRIBUTES_AND_TYPES = {
  [TEMPORAL_CUSTOM_SEARCH_ATTRIBUTES.SYNC_ID]: IndexedValueType.INDEXED_VALUE_TYPE_KEYWORD,
  [TEMPORAL_CUSTOM_SEARCH_ATTRIBUTES.APPLICATION_ID]: IndexedValueType.INDEXED_VALUE_TYPE_KEYWORD,
  [TEMPORAL_CUSTOM_SEARCH_ATTRIBUTES.CUSTOMER_ID]: IndexedValueType.INDEXED_VALUE_TYPE_KEYWORD,
  [TEMPORAL_CUSTOM_SEARCH_ATTRIBUTES.INTEGRATION_ID]: IndexedValueType.INDEXED_VALUE_TYPE_KEYWORD,
  [TEMPORAL_CUSTOM_SEARCH_ATTRIBUTES.PROVIDER_ID]: IndexedValueType.INDEXED_VALUE_TYPE_KEYWORD,
  [TEMPORAL_CUSTOM_SEARCH_ATTRIBUTES.SYNC_CONFIG_ID]: IndexedValueType.INDEXED_VALUE_TYPE_KEYWORD,
  [TEMPORAL_CUSTOM_SEARCH_ATTRIBUTES.CONNECTION_ID]: IndexedValueType.INDEXED_VALUE_TYPE_KEYWORD,
  [TEMPORAL_CUSTOM_SEARCH_ATTRIBUTES.PROVIDER_CATEGORY]: IndexedValueType.INDEXED_VALUE_TYPE_KEYWORD,
  [TEMPORAL_CUSTOM_SEARCH_ATTRIBUTES.PROVIDER_NAME]: IndexedValueType.INDEXED_VALUE_TYPE_KEYWORD,
};
