type: object
properties:
  destination_id:
    type: string
    example: 6e7baa88-84dd-4dbc-902a-14522c2984eb
  provider_id:
    type: string
    example: 7f72ec07-e5c1-47fd-8cf5-e71dd13873af
  config:
    $ref: ./objects/sync_config_data.yaml
required:
  - application_id
  - destination_id
  - provider_id
  - config
