nmHoistingLimits: none

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.4.1.cjs

npmScopes:
  buf:
    npmRegistryServer: https://buf.build/gen/npm/v1

supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - linux
    - darwin
