nmHoistingLimits: workspaces

nodeLinker: node-modules

npmPublishAccess: public

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-3.3.1.cjs

packageExtensions:
  '@docsearch/react@*':
    dependencies:
      '@algolia/client-search': '4.14.3'
