services:
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-supaglue}

  api:
    image: supaglue/api:0.3.3
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_started
    environment:
      - NODE_ENV=production
      - SUPAGLUE_SYNC_PERIOD_MS
      - SUPAGLUE_DATABASE_URL=${SUPAGLUE_DATABASE_URL:-postgres://postgres:supaglue@postgres:5432/postgres?schema=api}
      - SUPAGLUE_API_PORT=${SUPAGLUE_API_PORT:-8080}
      - SUPAGLUE_CORS_ORIGIN=${SUPAGLUE_CORS_ORIGIN:-http://localhost:3000}
      - SUPAGLUE_DISABLE_ANALYTICS
      - SUPAGLUE_DISABLE_ERROR_REPORTING
      - SUPAGLUE_POSTHOG_API_KEY
    restart: on-failure

  sync-worker:
    image: supaglue/sync-worker:0.3.3
    depends_on:
      postgres:
        condition: service_started
    environment:
      - NODE_ENV=production
      - SUPAGLUE_DATABASE_URL=${SUPAGLUE_DATABASE_URL:-postgres://postgres:supaglue@postgres:5432/postgres?schema=api}
      - SUPAGLUE_DISABLE_ANALYTICS
      - SUPAGLUE_DISABLE_ERROR_REPORTING
      - SUPAGLUE_POSTHOG_API_KEY
    restart: on-failure

  temporal:
    image: slamdev/temporalite:0.3.0 # TODO: we should replace this with one hosted by us later
    ports:
      - 7233:7233
      - 8233:8233
    entrypoint: temporalite start -n default --ip 0.0.0.0 -f /data/temporal.db
    restart: on-failure
    volumes:
      - temporalitedata:/data

volumes:
  pgdata:
  temporalitedata:
