services:
  api:
    volumes:
      - ${SUPAGLUE_CONFIG_DIR:-~/.supaglue}:/root/.supaglue
    depends_on:
      postgres:
        condition: service_started
      init:
        condition: service_completed_successfully
    environment:
      - SUPAGLUE_PRETTY_LOGS=1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  sync-worker:
    volumes:
      - ${SUPAGLUE_CONFIG_DIR:-~/.supaglue}:/root/.supaglue
    environment:
      - SUPAGLUE_PRETTY_LOGS=1
    depends_on:
      postgres:
        condition: service_started
      init:
        condition: service_completed_successfully

  init:
    image: supaglue/init
    environment:
      - SUPAGLUE_DATABASE_URL=${SUPAGLUE_DATABASE_URL:-postgres://postgres:supaglue@postgres:5432/postgres?schema=api}
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - ./packages/db/prisma:/app/packages/db/prisma
      - .env:/app/.env
    working_dir: /app
