services:
  api:
    image: node:18
    volumes:
      - .:/app
    command: /bin/sh -c "./apps/api/scripts/start_dev.sh"
    environment:
      - NODE_ENV=development
      - SUPAGLUE_DATABASE_URL=${SUPAGLUE_DATABASE_URL:-postgres://postgres:supaglue@postgres:5432/postgres?schema=api}
      - SUPAGLUE_API_SERVER_URL=${SUPAGLUE_API_SERVER_URL:-http://localhost:8080}
      - SUPAGLUE_API_PORT=${SUPAGLUE_API_PORT:-8080}
      - SUPAGLUE_API_ENCRYPTION_SECRET=${SUPAGLUE_API_ENCRYPTION_SECRET:-myververysecuresecret}
      - SUPAGLUE_DISABLE_ANALYTICS=${SUPAGLUE_DISABLE_ANALYTICS:-1}
      - SUPAGLUE_DISABLE_ERROR_REPORTING=${SUPAGLUE_DISABLE_ERROR_REPORTING:-1}
      - SUPAGLUE_PRETTY_LOGS=${SUPAGLUE_PRETTY_LOGS:-1}
      - SUPAGLUE_LOG_LEVEL=${SUPAGLUE_LOG_LEVEL:-debug}
      - SUPAGLUE_POSTHOG_API_KEY
