x-common-env: &common-env
  NODE_ENV: production
  SUPAGLUE_ENVIRONMENT: docker
  SUPAGLUE_DATABASE_URL: ${SUPAGLUE_DATABASE_URL:-postgres://postgres:supaglue@postgres:5432/postgres?schema=api}
  SUPAGLUE_PRETTY_LOGS: 1
  SUPAGLUE_POSTHOG_API_KEY: ${SUPAGLUE_POSTHOG_API_KEY:-phc_thv3N2dFQcJDh2vPz6FtGE9oKDiBSdYp5oKS1Cu9U8j}
  SUPAGLUE_API_ENCRYPTION_SECRET: ${SUPAGLUE_API_ENCRYPTION_SECRET:-some-per-customer-secret-salt}
  SVIX_API_TOKEN: ${SVIX_API_TOKEN:-testsk_sLr_YXpHsUKnVZFQSPH17YIXbBGn9Nl3.us}
  SUPAGLUE_LOG_LEVEL: info
  SUPAGLUE_DISABLE_ERROR_REPORTING: 1
  SUPAGLUE_DISABLE_ANALYTICS:
  SUPAGLUE_DEPLOYMENT_ID:
  SALESFORCE_CLIENT_ID:
  SALESFORCE_CLIENT_SECRET:
  HUBSPOT_CLIENT_ID:
  HUBSPOT_CLIENT_SECRET:
  GONG_CLIENT_ID:
  GONG_CLIENT_SECRET:
  OUTREACH_CLIENT_ID:
  OUTREACH_CLIENT_SECRET:
  SALESLOFT_CLIENT_ID:
  SALESLOFT_CLIENT_SECRET:

x-fe-api-common-env: &fe-api-common-env
  SUPAGLUE_INTERNAL_TOKEN: some-internal-token
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:-some-key}
  CLERK_SECRET_KEY: ${CLERK_SECRET_KEY:-some-key}
  NEXT_PUBLIC_SUPAGLUE_ENVIRONMENT: docker
  NEXT_PUBLIC_SUPAGLUE_DISABLE_ERROR_REPORTING: 1

services:
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-supaglue}

  api:
    image: supaglue/api:0.13.11
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_started
      init:
        condition: service_completed_successfully
    volumes:
      - ${SUPAGLUE_CONFIG_DIR:-~/.supaglue}:/root/.supaglue
    environment:
      <<: [*common-env, *fe-api-common-env]
      SUPAGLUE_API_PORT: ${SUPAGLUE_API_PORT:-8080}
      SUPAGLUE_CORS_ORIGIN: ${SUPAGLUE_CORS_ORIGIN:-http://localhost:3000}
      SUPAGLUE_SYNC_PERIOD_MS:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
    restart: on-failure

  sync-worker:
    image: supaglue/sync-worker:0.13.11
    depends_on:
      postgres:
        condition: service_started
      init:
        condition: service_completed_successfully
    volumes:
      - ${SUPAGLUE_CONFIG_DIR:-~/.supaglue}:/root/.supaglue
    environment:
      <<: *common-env
    restart: on-failure

  mgmt-ui:
    image: supaglue/mgmt-ui:0.13.11
    ports:
      - '3000:3000'
    depends_on:
      api:
        condition: service_started
      init:
        condition: service_completed_successfully
    environment:
      <<: *fe-api-common-env
      SUPAGLUE_API_HOST: ${SUPAGLUE_API_HOST:-http://api:8080}
      SUPAGLUE_JWT_SECRET: ${SUPAGLUE_JWT_SECRET:-a-secret-to-change}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      SUPAGLUE_DEPLOYMENT_ID:
    restart: on-failure

  temporal:
    image: alpine:3.18.0
    ports:
      - 7233:7233
      - 8233:8233
    restart: on-failure
    command:
      - /bin/sh
      - -c
      - |
        apk add --update curl
        rm -rf /var/cache/apk/*
        curl -sSf https://temporal.download/cli.sh | sh
        /root/.temporalio/bin/temporal server start-dev -n default --ip 0.0.0.0 -f /data/temporal.db
    volumes:
      - temporalitedata:/data

  salesforce-pub-sub:
    image: supaglue/salesforce-pub-sub:0.13.11
    environment:
      <<: *common-env
    restart: on-failure
    depends_on:
      postgres:
        condition: service_started
      init:
        condition: service_completed_successfully

  init:
    image: supaglue/api:0.13.11
    environment:
      <<: *common-env
      SUPAGLUE_QUICKSTART_API_KEY: ${SUPAGLUE_QUICKSTART_API_KEY:-some-api-key}
      DO_SEED: '1'
    depends_on:
      postgres:
        condition: service_started
      temporal:
        condition: service_started
    volumes:
      - .env:/app/.env
    command:
      - sh
      - -c
      - |
        npx prisma@4.12.0 migrate deploy
        node node_modules/@supaglue/db/prisma/seed.js
        node init_scripts/init_temporal.js

volumes:
  pgdata:
  temporalitedata:
