x-common-env:
  &common-env
  NODE_ENV: development
  SUPAGLUE_ENVIRONMENT: development
  SUPAGLUE_PRETTY_LOGS: 1
  SUPAGLUE_LOG_LEVEL: debug
  SUPAGLUE_DISABLE_ANALYTICS: 1
  # Edit this when using ngrok
  SUPAGLUE_SERVER_URL: http://localhost:8080

services:
  api:
    image: node:18
    environment:
      <<: *common-env
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "./apps/api/scripts/start_dev.sh"

  sync-worker:
    image: node:18
    environment:
      <<: *common-env
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "./apps/sync-worker/scripts/start_dev.sh"

  salesforce-pub-sub:
    image: node:18
    environment:
      <<: *common-env
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "./apps/salesforce-pub-sub/scripts/start_dev.sh"

  mgmt-ui:
    profiles:
      - donotstart

  init:
    image: node:18
    environment:
      <<: *common-env
      DO_SEED: "0"
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "yarn workspace @supaglue/db prisma migrate dev && yarn workspace @supaglue/db prisma db seed"
