/*
 * Supaglue Management API
 * # Introduction  Welcome to the Supaglue Management API documentation. You can use this API to manage customer integrations and connections.  ### Base API URL  ``` http://localhost:8080/mgmt/v1 ``` 
 *
 * OpenAPI spec version: 0.4.1
 * Contact: docs@supaglue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * IntegrationConfigSync
 */


public class IntegrationConfigSync {
  @SerializedName("period_ms")
  private Object periodMs = null;

  public IntegrationConfigSync periodMs(Object periodMs) {
    this.periodMs = periodMs;
    return this;
  }

   /**
   * Get periodMs
   * @return periodMs
  **/
  @Schema(example = "60000", required = true, description = "")
  public Object getPeriodMs() {
    return periodMs;
  }

  public void setPeriodMs(Object periodMs) {
    this.periodMs = periodMs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationConfigSync integrationConfigSync = (IntegrationConfigSync) o;
    return Objects.equals(this.periodMs, integrationConfigSync.periodMs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(periodMs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationConfigSync {\n");
    
    sb.append("    periodMs: ").append(toIndentedString(periodMs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
