/*
 * Supaglue Management API
 * # Introduction  Welcome to the Supaglue Management API documentation. You can use this API to manage customer integrations and connections.  ### Base API URL  ``` http://localhost:8080/mgmt/v1 ``` 
 *
 * OpenAPI spec version: 0.6.0
 * Contact: docs@supaglue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SyncInfo
 */


public class SyncInfo {
  @SerializedName("model_name")
  private Object modelName = null;

  @SerializedName("last_sync_start")
  private Object lastSyncStart = null;

  @SerializedName("next_sync_start")
  private Object nextSyncStart = null;

  @SerializedName("status")
  private Object status = null;

  @SerializedName("application_id")
  private Object applicationId = null;

  @SerializedName("customer_id")
  private Object customerId = null;

  @SerializedName("provider_name")
  private Object providerName = null;

  @SerializedName("category")
  private Object category = null;

  @SerializedName("connection_id")
  private Object connectionId = null;

  public SyncInfo modelName(Object modelName) {
    this.modelName = modelName;
    return this;
  }

   /**
   * Get modelName
   * @return modelName
  **/
  @Schema(example = "Account", required = true, description = "")
  public Object getModelName() {
    return modelName;
  }

  public void setModelName(Object modelName) {
    this.modelName = modelName;
  }

  public SyncInfo lastSyncStart(Object lastSyncStart) {
    this.lastSyncStart = lastSyncStart;
    return this;
  }

   /**
   * Get lastSyncStart
   * @return lastSyncStart
  **/
  @Schema(example = "2023-02-22T19:55:17.559Z", required = true, description = "")
  public Object getLastSyncStart() {
    return lastSyncStart;
  }

  public void setLastSyncStart(Object lastSyncStart) {
    this.lastSyncStart = lastSyncStart;
  }

  public SyncInfo nextSyncStart(Object nextSyncStart) {
    this.nextSyncStart = nextSyncStart;
    return this;
  }

   /**
   * Get nextSyncStart
   * @return nextSyncStart
  **/
  @Schema(example = "2023-02-22T20:55:17.559Z", required = true, description = "")
  public Object getNextSyncStart() {
    return nextSyncStart;
  }

  public void setNextSyncStart(Object nextSyncStart) {
    this.nextSyncStart = nextSyncStart;
  }

  public SyncInfo status(Object status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public Object getStatus() {
    return status;
  }

  public void setStatus(Object status) {
    this.status = status;
  }

  public SyncInfo applicationId(Object applicationId) {
    this.applicationId = applicationId;
    return this;
  }

   /**
   * Get applicationId
   * @return applicationId
  **/
  @Schema(example = "974125fa-ffb6-47fc-b12f-44c566fc5da1", required = true, description = "")
  public Object getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(Object applicationId) {
    this.applicationId = applicationId;
  }

  public SyncInfo customerId(Object customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/
  @Schema(example = "my-customer-1", required = true, description = "")
  public Object getCustomerId() {
    return customerId;
  }

  public void setCustomerId(Object customerId) {
    this.customerId = customerId;
  }

  public SyncInfo providerName(Object providerName) {
    this.providerName = providerName;
    return this;
  }

   /**
   * Get providerName
   * @return providerName
  **/
  @Schema(example = "hubspot", required = true, description = "")
  public Object getProviderName() {
    return providerName;
  }

  public void setProviderName(Object providerName) {
    this.providerName = providerName;
  }

  public SyncInfo category(Object category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @Schema(required = true, description = "")
  public Object getCategory() {
    return category;
  }

  public void setCategory(Object category) {
    this.category = category;
  }

  public SyncInfo connectionId(Object connectionId) {
    this.connectionId = connectionId;
    return this;
  }

   /**
   * Get connectionId
   * @return connectionId
  **/
  @Schema(example = "3217ea51-11c8-43c9-9547-6f197e02e5e4", required = true, description = "")
  public Object getConnectionId() {
    return connectionId;
  }

  public void setConnectionId(Object connectionId) {
    this.connectionId = connectionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SyncInfo syncInfo = (SyncInfo) o;
    return Objects.equals(this.modelName, syncInfo.modelName) &&
        Objects.equals(this.lastSyncStart, syncInfo.lastSyncStart) &&
        Objects.equals(this.nextSyncStart, syncInfo.nextSyncStart) &&
        Objects.equals(this.status, syncInfo.status) &&
        Objects.equals(this.applicationId, syncInfo.applicationId) &&
        Objects.equals(this.customerId, syncInfo.customerId) &&
        Objects.equals(this.providerName, syncInfo.providerName) &&
        Objects.equals(this.category, syncInfo.category) &&
        Objects.equals(this.connectionId, syncInfo.connectionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(modelName, lastSyncStart, nextSyncStart, status, applicationId, customerId, providerName, category, connectionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SyncInfo {\n");
    
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    lastSyncStart: ").append(toIndentedString(lastSyncStart)).append("\n");
    sb.append("    nextSyncStart: ").append(toIndentedString(nextSyncStart)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    providerName: ").append(toIndentedString(providerName)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    connectionId: ").append(toIndentedString(connectionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
