{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supaglue.componentname" (list . "api") }}
  labels:
    app.kubernetes.io/name: {{ include "supaglue.name" . }}
    helm.sh/chart: {{ include "supaglue.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "supaglue.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "supaglue.name" . }}
        helm.sh/chart: {{ include "supaglue.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        {{- with .Values.api.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.api.metrics.annotations.enabled }}
        prometheus.io/job: {{ .Chart.Name }}-api
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
        {{- end }}
        {{- with .Values.api.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{ include "supaglue.serviceAccount" . }}
      initContainers:
        - name: wait-for-database
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 {{ template "supaglue.databaseHost" . }} {{ template "supaglue.databasePort" $ }}; do echo waiting for database; sleep 2; done;']
        - name: wait-for-temporal
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 {{ template "supaglue.temporalHost" . }} {{ template "supaglue.temporalPort" $ }}; do echo waiting for temporal; sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ default "supaglue/api" .Values.api.image.repository }}:{{ default .Chart.AppVersion .Values.api.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.api.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: production
            - name: SUPAGLUE_API_PORT
              value: {{ .Values.api.service.port | quote }}
            - name: SUPAGLUE_DISABLE_ERROR_REPORTING
              value: "1"
            - name: DISABLE_BANNER
              value: "1"
            - name: SUPAGLUE_SERVER_URL
              value: {{ required "api.serverUrl is required" .Values.api.serverUrl }}
            - name: SUPAGLUE_OAUTH_RETURN_URL
              value: {{ required "api.oauthReturnUrl is required" .Values.api.oauthReturnUrl }}
            - name: SUPAGLUE_LOG_LEVEL
              value: {{ .Values.api.logLevel }}
            - name: SUPAGLUE_CORS_ORIGIN
              value: {{ required "api.corsOrigin is required" .Values.api.corsOrigin }}
            - name: SUPAGLUE_TEMPORAL_HOST
              value: {{ template "supaglue.temporalHost" . }}
            - name: SUPAGLUE_TEMPORAL_PORT
              value: {{ include "supaglue.temporalPort" . | quote }}
            - name: SUPAGLUE_API_ENCRYPTION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "supaglue.secretName" . }}
                  key: {{ .Values.secretKeys.dbEncryptionSecret }}
            - name: SUPAGLUE_API_KEY_SALT
              valueFrom:
                secretKeyRef:
                  name: {{ template "supaglue.secretName" . }}
                  key: {{ .Values.secretKeys.apiKeySalt }}
            - name: SUPAGLUE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "supaglue.secretName" . }}
                  key: {{ .Values.secretKeys.databaseUrl }}
            - name: SUPAGLUE_INTERNAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "supaglue.secretName" . }}
                  key: {{ .Values.secretKeys.internalApiToken }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "supaglue.secretName" . }}
                  key: {{ .Values.secretKeys.adminPassword }}
            - name: SUPAGLUE_DEPLOYMENT_ID
              value: {{ include "supaglue.deploymentId" . }}
            {{- with .Values.api.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
            # TODO uncomment when we are producing metrics
            # - name: metrics
            #   containerPort: 9090
            #   protocol: TCP
          livenessProbe:
              initialDelaySeconds: 30
              httpGet:
                path: /health
                port: http
          readinessProbe:
              initialDelaySeconds: 30
              httpGet:
                path: /health
                port: http
          volumeMounts:
            {{- if .Values.api.additionalVolumeMounts }}
            {{- toYaml .Values.api.additionalVolumeMounts | nindent 12}}
            {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
        {{- if .Values.api.sidecarContainers }}
        {{- toYaml .Values.api.sidecarContainers | nindent 8 }}
        {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.api.additionalVolumes }}
        {{- toYaml .Values.api.additionalVolumes | nindent 8}}
        {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
