get:
  operationId: getConnectionSyncConfig
  summary: Get connection sync config
  tags:
    - ConnectionSyncConfigs
  security:
    - x-api-key: []
  parameters: []
  responses:
    '200':
      description: Connection Sync Config
      content:
        application/json:
          schema:
            $ref: ../components/schemas/objects/connection_sync_config.yaml
    '400':
      $ref: ../../../common/components/responses/badRequest.yaml
    '401':
      $ref: ../../../common/components/responses/unauthorized.yaml
    '403':
      $ref: ../../../common/components/responses/forbidden.yaml
    '404':
      $ref: ../../../common/components/responses/notFound.yaml
    '499':
      $ref: ../../../common/components/responses/remoteProviderError.yaml
    '500':
      $ref: ../../../common/components/responses/internalServerError.yaml
    '501':
      $ref: ../../../common/components/responses/notImplemented.yaml
put:
  operationId: upsertConnectionSyncConfig
  summary: Upsert connection sync config
  description: Use this to override SyncConfig and Destination configurations on a per customer-connection basis. E.g. you can override the objects that are synced per customer-connection as well as override the table/collection that these objects are written into.
  tags:
    - ConnectionSyncConfigs
  security:
    - x-api-key: []
  parameters: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../components/schemas/upsert_connection_sync_config.yaml
  responses:
    '200':
      description: Connection Sync Config
      content:
        application/json:
          schema:
            $ref: ../components/schemas/objects/connection_sync_config.yaml
    '400':
      $ref: ../../../common/components/responses/badRequest.yaml
    '401':
      $ref: ../../../common/components/responses/unauthorized.yaml
    '403':
      $ref: ../../../common/components/responses/forbidden.yaml
    '404':
      $ref: ../../../common/components/responses/notFound.yaml
    '409':
      $ref: ../../../common/components/responses/conflict.yaml
    '422':
      $ref: ../../../common/components/responses/unprocessableEntity.yaml
    '500':
      $ref: ../../../common/components/responses/internalServerError.yaml
    '501':
      $ref: ../../../common/components/responses/notImplemented.yaml
delete:
  operationId: deleteConnectionSyncConfig
  summary: Delete connection sync config
  tags:
    - ConnectionSyncConfigs
  security:
    - x-api-key: []
  responses:
    '204':
      description: Connection Sync Config
    '400':
      $ref: ../../../common/components/responses/badRequest.yaml
    '401':
      $ref: ../../../common/components/responses/unauthorized.yaml
    '403':
      $ref: ../../../common/components/responses/forbidden.yaml
    '404':
      $ref: ../../../common/components/responses/notFound.yaml
    '409':
      $ref: ../../../common/components/responses/conflict.yaml
    '422':
      $ref: ../../../common/components/responses/unprocessableEntity.yaml
    '500':
      $ref: ../../../common/components/responses/internalServerError.yaml
    '501':
      $ref: ../../../common/components/responses/notImplemented.yaml
parameters:
  - $ref: ../../../common/components/parameters/header/x-customer-id.yaml
  - $ref: ../../../common/components/parameters/header/x-provider-name.yaml
