put:
  operationId: upsertConnectionSyncConfig
  summary: Upsert connection sync config
  tags:
    - SchemaMappings
  security:
    - x-api-key: []
  parameters: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../components/schemas/upsert_connection_sync_config.yaml
  responses:
    '200':
      description: Connection Sync Config
      content:
        application/json:
          schema:
            $ref: ../components/schemas/objects/connection_sync_config.yaml
parameters:
  - $ref: ../../../common/components/parameters/header/x-customer-id.yaml
  - $ref: ../../../common/components/parameters/header/x-provider-name.yaml
