get:
  operationId: getSyncConfig
  summary: Get Sync Config
  tags:
    - SyncConfigs
  security:
    - x-api-key: []
  responses:
    200:
      description: SyncConfig
      content:
        application/json:
          schema:
            $ref: ../components/schemas/objects/sync_config.yaml
put:
  operationId: updateSyncConfig
  summary: Update Sync Config
  description: |
    :::danger
    If `force_delete_syncs` is set to true, any syncs for any deleted objects will be cascadingly deleted for all customers with this sync config.
    :::
  tags:
    - SyncConfigs
  parameters:
    - name: force_delete_syncs
      in: query
      required: false
      schema: 
        type: boolean
      description: If true, any syncs for any deleted objects will be cascadingly deleted for all customers with this sync config
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../components/schemas/update_sync_config.yaml
  responses:
    200:
      description: SyncConfig
      content:
        application/json:
          schema:
            $ref: ../components/schemas/objects/sync_config.yaml
delete:
  operationId: deleteSyncConfig
  summary: Delete Sync Config
  description: |
    :::danger
    If `force_delete_syncs` is set to true, all syncs for all customers with this sync config will be cascadingly deleted.
    :::
  tags:
    - SyncConfigs
  security:
    - x-api-key: []
  parameters:
    - name: force_delete_syncs
      in: query
      required: false
      schema: 
        type: boolean
      description: If true, all syncs for all customers with this sync config will be cascadingly deleted
  responses:
    200:
      description: SyncConfig
      content:
        application/json:
          schema:
            $ref: ../components/schemas/objects/sync_config.yaml
parameters:
  - name: sync_config_id
    in: path
    required: true
    schema:
      type: string
    example: d583ec72-55d4-4f35-9668-f6c759674cc1
