get:
  operationId: getSyncConfigs
  tags:
    - SyncConfigs
  security:
    - x-api-key: []
  summary: List Sync Configs
  description: >-
    Get a list of Sync Configs
  responses:
    '200':
      description: SyncConfigs
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../components/schemas/objects/sync_config.yaml
post:
  operationId: createSyncConfig
  summary: Create Sync Config
  tags:
    - SyncConfigs
  security:
    - x-api-key: []
  parameters: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../components/schemas/create_update_sync_config.yaml
  responses:
    '201':
      description: SyncConfig created
      content:
        application/json:
          schema:
            $ref: ../components/schemas/objects/sync_config.yaml
