get:
  operationId: getSyncConfig
  summary: Get Sync Config
  tags:
    - SyncConfigs
  security:
    - x-api-key: []
  responses:
    200:
      description: SyncConfig
      content:
        application/json:
          schema:
            $ref: ../components/schemas/objects/sync_config.yaml
          examples:
            Example:
              value:
                id: a91c434a-6f75-4f5f-85f9-90fd7caa168f
                destination_id: 0a292508-d254-4929-98d3-dc23416efff8
                provider_id: ebd1e697-0e4d-4c01-8622-c8c03703ef68
                config:
                  default_config:
                    period_ms: 60000
                    strategy: full then incremental
                  common_objects:
                    - object: contacts
                    - object: accounts
                  standard_objects:
                    - object: emails
                    - object: tasks
put:
  operationId: updateSyncConfig
  summary: Update Sync Config
  tags:
    - SyncConfigs
  parameters: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../components/schemas/create_update_sync_config.yaml
  responses:
    200:
      description: SyncConfig
      content:
        application/json:
          schema:
            $ref: ../components/schemas/objects/sync_config.yaml
          examples:
            Example:
              value:
                id: 7a34a7bb-193a-4cca-ac16-63ef739995e1
                destination_id: 0a292508-d254-4929-98d3-dc23416efff8
                provider_id: ebd1e697-0e4d-4c01-8622-c8c03703ef68
                config:
                  default_config:
                    period_ms: 60000
                    strategy: full then incremental
                  common_objects:
                    - object: contacts
                    - object: accounts
                  standard_objects:
                    - object: emails
                    - object: tasks
delete:
  operationId: deleteSyncConfig
  summary: Delete Sync Config
  tags:
    - SyncConfigs
  security:
    - x-api-key: []
  responses:
    200:
      description: SyncConfig
      content:
        application/json:
          schema:
            $ref: ../components/schemas/objects/sync_config.yaml
          examples:
            Example:
              value:
                id: ee2b63fa-edec-4875-b2f5-921d3b13ca83
                destination_id: 0a292508-d254-4929-98d3-dc23416efff8
                provider_id: ebd1e697-0e4d-4c01-8622-c8c03703ef68
                config:
                  default_config:
                    period_ms: 60000
                    strategy: full then incremental
                  common_objects:
                    - object: contacts
                    - object: accounts
                  standard_objects:
                    - object: emails
                    - object: tasks
parameters:
  - name: sync_config_id
    in: path
    required: true
    schema:
      type: string
      example: d583ec72-55d4-4f35-9668-f6c759674cc1
