/*
 * Supaglue CRM API
 * # Introduction  Welcome to the Supaglue unified CRM API documentation. You can use this API to read data that has been synced into Supaglue from third-party providers.  ### Base API URL  ``` http://localhost:8080/crm/v1 ``` 
 *
 * OpenAPI spec version: 0.6.0
 * Contact: docs@supaglue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Addresses;
import io.swagger.client.model.CustomFields;
import io.swagger.client.model.LifecycleStage;
import io.swagger.client.model.PhoneNumbers;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CreateUpdateAccount
 */


public class CreateUpdateAccount {
  @SerializedName("description")
  private String description = null;

  @SerializedName("industry")
  private String industry = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("number_of_employees")
  private Integer numberOfEmployees = null;

  @SerializedName("website")
  private String website = null;

  @SerializedName("addresses")
  private Addresses addresses = null;

  @SerializedName("phone_numbers")
  private PhoneNumbers phoneNumbers = null;

  @SerializedName("owner_id")
  private String ownerId = null;

  @SerializedName("lifecycle_stage")
  private LifecycleStage lifecycleStage = null;

  @SerializedName("custom_fields")
  private CustomFields customFields = null;

  public CreateUpdateAccount description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(example = "Integration API", description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreateUpdateAccount industry(String industry) {
    this.industry = industry;
    return this;
  }

   /**
   * Get industry
   * @return industry
  **/
  @Schema(example = "API's", description = "")
  public String getIndustry() {
    return industry;
  }

  public void setIndustry(String industry) {
    this.industry = industry;
  }

  public CreateUpdateAccount name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(example = "Sample Customer", description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateUpdateAccount numberOfEmployees(Integer numberOfEmployees) {
    this.numberOfEmployees = numberOfEmployees;
    return this;
  }

   /**
   * Get numberOfEmployees
   * @return numberOfEmployees
  **/
  @Schema(example = "276000", description = "")
  public Integer getNumberOfEmployees() {
    return numberOfEmployees;
  }

  public void setNumberOfEmployees(Integer numberOfEmployees) {
    this.numberOfEmployees = numberOfEmployees;
  }

  public CreateUpdateAccount website(String website) {
    this.website = website;
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  @Schema(example = "https://supaglue.com/", description = "")
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }

  public CreateUpdateAccount addresses(Addresses addresses) {
    this.addresses = addresses;
    return this;
  }

   /**
   * Get addresses
   * @return addresses
  **/
  @Schema(description = "")
  public Addresses getAddresses() {
    return addresses;
  }

  public void setAddresses(Addresses addresses) {
    this.addresses = addresses;
  }

  public CreateUpdateAccount phoneNumbers(PhoneNumbers phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
    return this;
  }

   /**
   * Get phoneNumbers
   * @return phoneNumbers
  **/
  @Schema(description = "")
  public PhoneNumbers getPhoneNumbers() {
    return phoneNumbers;
  }

  public void setPhoneNumbers(PhoneNumbers phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
  }

  public CreateUpdateAccount ownerId(String ownerId) {
    this.ownerId = ownerId;
    return this;
  }

   /**
   * Get ownerId
   * @return ownerId
  **/
  @Schema(example = "9f3e97fd-4d5d-4efc-959d-bbebfac079f5", description = "")
  public String getOwnerId() {
    return ownerId;
  }

  public void setOwnerId(String ownerId) {
    this.ownerId = ownerId;
  }

  public CreateUpdateAccount lifecycleStage(LifecycleStage lifecycleStage) {
    this.lifecycleStage = lifecycleStage;
    return this;
  }

   /**
   * Get lifecycleStage
   * @return lifecycleStage
  **/
  @Schema(description = "")
  public LifecycleStage getLifecycleStage() {
    return lifecycleStage;
  }

  public void setLifecycleStage(LifecycleStage lifecycleStage) {
    this.lifecycleStage = lifecycleStage;
  }

  public CreateUpdateAccount customFields(CustomFields customFields) {
    this.customFields = customFields;
    return this;
  }

   /**
   * Get customFields
   * @return customFields
  **/
  @Schema(description = "")
  public CustomFields getCustomFields() {
    return customFields;
  }

  public void setCustomFields(CustomFields customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateUpdateAccount createUpdateAccount = (CreateUpdateAccount) o;
    return Objects.equals(this.description, createUpdateAccount.description) &&
        Objects.equals(this.industry, createUpdateAccount.industry) &&
        Objects.equals(this.name, createUpdateAccount.name) &&
        Objects.equals(this.numberOfEmployees, createUpdateAccount.numberOfEmployees) &&
        Objects.equals(this.website, createUpdateAccount.website) &&
        Objects.equals(this.addresses, createUpdateAccount.addresses) &&
        Objects.equals(this.phoneNumbers, createUpdateAccount.phoneNumbers) &&
        Objects.equals(this.ownerId, createUpdateAccount.ownerId) &&
        Objects.equals(this.lifecycleStage, createUpdateAccount.lifecycleStage) &&
        Objects.equals(this.customFields, createUpdateAccount.customFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, industry, name, numberOfEmployees, website, addresses, phoneNumbers, ownerId, lifecycleStage, customFields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateUpdateAccount {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    numberOfEmployees: ").append(toIndentedString(numberOfEmployees)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    phoneNumbers: ").append(toIndentedString(phoneNumbers)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    lifecycleStage: ").append(toIndentedString(lifecycleStage)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
