type: object
properties:
  host:
    type: string
    example: https://mydb.com
  port:
    type: number
    example: 5432
  database:
    type: string
    example: my_database
  schema:
    type: string
    example: public
  user:
    type: string
    example: myuser
  password:
    type: string
    example: password
  sslmode:
    type: string
    enum:
      - disable
      - require
    example: require
  sslaccept:
    type: string
    enum:
      - strict
      - accept_invalid_certs
    example: strict
  ca:
    type: string
    example: -----BEGIN CERTIFICATE-----\nMIID...
  cert:
    type: string
    example: -----BEGIN CERTIFICATE-----\nMIID...
  key:
    type: string
    example: -----RSA PRIVATE KEY-----\nMIIE...
  passphrase:
    type: string
    example: password

required:
  - host
  - port
  - database
  - schema
  - user
  - password
  - sslmode
  - sslaccept
  - ca
  - cert
  - key
  - passphrase
