openapi: 3.0.3
info:
  version: 0.7.6
  title: Supaglue Engagement API
  contact:
    name: Supaglue
    email: docs@supaglue.com
    url: 'https://supaglue.com'
  description: |
    # Introduction

    Welcome to the Supaglue unified Engagement API documentation. You can use this API to read data that has been synced into Supaglue from third-party providers.

    ### Base API URL

    ```
    http://localhost:8080/engagement/v1
    ```
externalDocs:
  description: Try out our API in Postman!
  url: 'https://www.postman.com/supaglue/workspace/supaglue-public/overview'
servers:
  - url: 'http://localhost:8080/engagement/v1'
    description: Local Supaglue API
paths:
  '/contacts':
    $ref: paths/contacts.yaml
  # '/contacts/{contact_id}':
  #   $ref: paths/contacts@{contact_id}.yaml
  '/sequences':
    $ref: paths/sequences.yaml
  # '/sequences/{sequence_id}':
  #   $ref: paths/sequences@{sequence_id}.yaml
tags:
  - name: Contacts
    description: The `Contact` Common Model is used to represent a "contact" in Engagements.
  - name: Sequences
    description: The `Sequence` Common Model is used to represent a "sequence" in Engagements.
  - name: Passthrough
    description: Passthrough operations to underlying providers.
components:
  securitySchemes:
    ApiKeyAuth:
      $ref: ../common/components/securitySchemes/x-api-key.yaml
  schemas:
    contact:
      $ref: ./components/schemas/objects/contact.yaml
    create_contact:
      $ref: ./components/schemas/create_contact.yaml
    sequence:
      $ref: ./components/schemas/objects/sequence.yaml
    create_sequence:
      $ref: ./components/schemas/create_sequence.yaml
    start_sequence:
      $ref: ./components/schemas/start_sequence.yaml
    pagination:
      $ref: ../common/components/schemas/pagination.yaml
    address:
      $ref: ./components/schemas/objects/address.yaml
    email_addresses:
      $ref: ./components/schemas/objects/email_addresses.yaml
    custom_fields:
      $ref: ./components/schemas/objects/custom_fields.yaml
  parameters:
    x-customer-id:
      $ref: ../common/components/parameters/header/x-customer-id.yaml
    x-provider-name:
      $ref: ../common/components/parameters/header/x-provider-name.yaml
