/* tslint:disable */
/* eslint-disable */
/**
 * Supaglue CRM API
 * # Introduction  Welcome to the Supaglue unified CRM API documentation. You can use this API to read data that has been synced into Supaglue from third-party providers.  ### Base API URL  ``` http://localhost:8080/crm/v1 ``` 
 *
 * OpenAPI spec version: 0.6.0
 * Contact: docs@supaglue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Account } from './account';
import { Addresses } from './addresses';
import { EmailAddresses } from './email-addresses';
import { LifecycleStage } from './lifecycle-stage';
import { PhoneNumbers } from './phone-numbers';
import { User } from './user';
/**
 * 
 * @export
 * @interface Contact
 */
export interface Contact {
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    accountId: string | null;
    /**
     * 
     * @type {Account}
     * @memberof Contact
     */
    account?: Account;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    ownerId: string | null;
    /**
     * 
     * @type {User}
     * @memberof Contact
     */
    owner?: User;
    /**
     * 
     * @type {Addresses}
     * @memberof Contact
     */
    addresses: Addresses;
    /**
     * 
     * @type {EmailAddresses}
     * @memberof Contact
     */
    emailAddresses: EmailAddresses;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    firstName: string | null;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    remoteId: string;
    /**
     * 
     * @type {Date}
     * @memberof Contact
     */
    lastActivityAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    lastName: string | null;
    /**
     * 
     * @type {PhoneNumbers}
     * @memberof Contact
     */
    phoneNumbers: PhoneNumbers;
    /**
     * 
     * @type {LifecycleStage}
     * @memberof Contact
     */
    lifecycleStage: LifecycleStage;
    /**
     * 
     * @type {Date}
     * @memberof Contact
     */
    remoteCreatedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Contact
     */
    remoteUpdatedAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof Contact
     */
    remoteWasDeleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Contact
     */
    lastModifiedAt?: Date;
}
