/* tslint:disable */
/* eslint-disable */
/**
 * Supaglue CRM API
 * # Introduction  Welcome to the Supaglue unified CRM API documentation. You can use this API to read data that has been synced into Supaglue from third-party providers.  ### Base API URL  ``` http://localhost:8080/crm/v1 ``` 
 *
 * OpenAPI spec version: 0.6.0
 * Contact: docs@supaglue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Addresses } from './addresses';
import { CustomFields } from './custom-fields';
import { LifecycleStage } from './lifecycle-stage';
import { PhoneNumbers } from './phone-numbers';
/**
 * 
 * @export
 * @interface CreateUpdateAccount
 */
export interface CreateUpdateAccount {
    /**
     * 
     * @type {string}
     * @memberof CreateUpdateAccount
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUpdateAccount
     */
    industry?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUpdateAccount
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateUpdateAccount
     */
    numberOfEmployees?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUpdateAccount
     */
    website?: string | null;
    /**
     * 
     * @type {Addresses}
     * @memberof CreateUpdateAccount
     */
    addresses?: Addresses;
    /**
     * 
     * @type {PhoneNumbers}
     * @memberof CreateUpdateAccount
     */
    phoneNumbers?: PhoneNumbers;
    /**
     * 
     * @type {string}
     * @memberof CreateUpdateAccount
     */
    ownerId?: string | null;
    /**
     * 
     * @type {LifecycleStage}
     * @memberof CreateUpdateAccount
     */
    lifecycleStage?: LifecycleStage;
    /**
     * 
     * @type {CustomFields}
     * @memberof CreateUpdateAccount
     */
    customFields?: CustomFields;
}
