/* tslint:disable */
/* eslint-disable */
/**
 * Supaglue CRM API
 * # Introduction  Welcome to the Supaglue unified CRM API documentation. You can use this API to read data that has been synced into Supaglue from third-party providers.  ### Base API URL  ``` http://localhost:8080/crm/v1 ``` 
 *
 * OpenAPI spec version: 0.4.1
 * Contact: docs@supaglue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Pagination } from './pagination';
import { User } from './user';
/**
 * 
 * @export
 * @interface InlineResponse2004
 */
export interface InlineResponse2004 extends Pagination {
    /**
     * 
     * @type {Array<User>}
     * @memberof InlineResponse2004
     */
    results?: Array<User>;
}
