import ApiKeyTabPanel from '@/components/configuration/ApiKeyTabPane';
import Header from '@/layout/Header';
import { getServerSideProps } from '@/pages';
import { Box, Tab, Tabs } from '@mui/material';
import Head from 'next/head';
import { useRouter } from 'next/router';
import * as React from 'react';
import { useState } from 'react';
import IntegrationTabPanelContainer from '../../components/configuration/IntegrationTabPanelContainer';

export { getServerSideProps };

type ConfigurationHeaderTab = {
  label: string;
  value: string;
};
const configurationHeaderTabs: ConfigurationHeaderTab[] = [
  {
    label: 'Integrations',
    value: 'integrations',
  },
  {
    label: 'API Keys',
    value: 'api_keys',
  },
];

interface TabPanelProps extends React.HTMLAttributes<HTMLDivElement> {
  children?: React.ReactNode;
  index: number;
  value: number;
}

function TabPanel(props: TabPanelProps) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`horizontal-tabpanel-${index}`}
      aria-labelledby={`horizontal-tab-${index}`}
      {...other}
    >
      {value === index && <Box sx={{ p: 3 }}>{children}</Box>}
    </div>
  );
}

export default function Home() {
  const router = useRouter();
  const [mobileOpen, setMobileOpen] = useState(false);
  const { tab = [] } = router.query;
  const [value, setValue] = React.useState(0);

  React.useEffect(() => {
    const tabIndex = configurationHeaderTabs.findIndex(
      (configurationHeaderTab) => configurationHeaderTab.value === tab[0]
    );
    setValue(tabIndex);
  }, [tab]);

  const handleChange = async (event: React.SyntheticEvent, newValue: number) => {
    let tab = configurationHeaderTabs[newValue].value;

    // default to crm
    if (newValue === 0) {
      tab += '/crm';
    }

    await router.push(`/configuration/${tab}`);
  };

  const handleDrawerToggle = () => {
    setMobileOpen(!mobileOpen);
  };

  return (
    <>
      <Head>
        <title>Supaglue Management Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
        <Header
          tabs={
            <Tabs value={value} textColor="inherit" onChange={handleChange}>
              <Tab label="Integrations" />
              <Tab label="API Key" />
            </Tabs>
          }
          title="Configuration"
          onDrawerToggle={handleDrawerToggle}
        />
        <Box component="main" sx={{ flex: 1, py: 6, px: 4, bgcolor: '#eaeff1' }}>
          <TabPanel value={value} index={0} className="w-full">
            <IntegrationTabPanelContainer />
          </TabPanel>
          <TabPanel value={value} index={1} className="w-full">
            <ApiKeyTabPanel />
          </TabPanel>
        </Box>
      </Box>
    </>
  );
}
