/* tslint:disable */
/* eslint-disable */
/**
 * Supaglue Management API
 * # Introduction  Welcome to the Supaglue Management API documentation. You can use this API to manage customer integrations and connections.  ### Base API URL  ``` http://localhost:8080/mgmt/v1 ``` 
 *
 * OpenAPI spec version: 0.3.3
 * Contact: docs@supaglue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ApplicationConfigWebhook
 */
export interface ApplicationConfigWebhook {
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigWebhook
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigWebhook
     */
    requestType: ApplicationConfigWebhookRequestTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationConfigWebhook
     */
    notifyOnSyncSuccess: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationConfigWebhook
     */
    notifyOnSyncError: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationConfigWebhook
     */
    notifyOnConnectionSuccess: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationConfigWebhook
     */
    notifyOnConnectionError: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ApplicationConfigWebhook
     */
    headers?: { [key: string]: any; };
}

/**
    * @export
    * @enum {string}
    */
export enum ApplicationConfigWebhookRequestTypeEnum {
    GET = 'GET',
    POST = 'POST',
    PUT = 'PUT',
    DELETE = 'DELETE',
    PATCH = 'PATCH'
}

