/* tslint:disable */
/* eslint-disable */
/**
 * Supaglue Customer API
 * # Introduction  Welcome to the Supaglue Management API documentation. You can use this API to manage customer integrations and connections.  ### Base API URL  ``` http://localhost:8080/mgmt/v1 ``` 
 *
 * OpenAPI spec version: 0.3.3
 * Contact: docs@supaglue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface IntegrationConfigSync
 */
export interface IntegrationConfigSync {
    /**
     * 
     * @type {number}
     * @memberof IntegrationConfigSync
     */
    periodMs: number;
}
