/* tslint:disable */
/* eslint-disable */
/**
 * Supaglue Management API
 * # Introduction  Welcome to the Supaglue Management API documentation. You can use this API to manage customer integrations and connections.  ### Base API URL  ``` http://localhost:8080/mgmt/v1 ``` 
 *
 * OpenAPI spec version: 0.6.0
 * Contact: docs@supaglue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SyncHistory
 */
export interface SyncHistory {
    /**
     * 
     * @type {any}
     * @memberof SyncHistory
     */
    modelName: any;
    /**
     * 
     * @type {any}
     * @memberof SyncHistory
     */
    errorMessage: any;
    /**
     * 
     * @type {any}
     * @memberof SyncHistory
     */
    startTimestamp: any;
    /**
     * 
     * @type {any}
     * @memberof SyncHistory
     */
    endTimestamp: any;
    /**
     * 
     * @type {any}
     * @memberof SyncHistory
     */
    applicationId: any;
    /**
     * 
     * @type {any}
     * @memberof SyncHistory
     */
    customerId: any;
    /**
     * 
     * @type {any}
     * @memberof SyncHistory
     */
    providerName: any;
    /**
     * 
     * @type {any}
     * @memberof SyncHistory
     */
    category: any;
    /**
     * 
     * @type {any}
     * @memberof SyncHistory
     */
    connectionId: any;
    /**
     * 
     * @type {any}
     * @memberof SyncHistory
     */
    status: any;
}
