# coding: utf-8

"""
    Supaglue API

    # Introduction  Welcome to the Supaglue unified CRM API documentation. You can use this API to read data that has been synced into Supaglue from third-party providers.  ### Base API URL  ``` http://localhost:8080/api/crm/v1 ```   # noqa: E501

    OpenAPI spec version: 0.3.0
    Contact: docs@supaglue.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response2003 import InlineResponse2003  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse2003(unittest.TestCase):
    """InlineResponse2003 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003(self):
        """Test InlineResponse2003"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response2003.InlineResponse2003()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
