# coding: utf-8

"""
    Supaglue API

    # Introduction  Welcome to the Supaglue unified CRM API documentation. You can use this API to read data that has been synced into Supaglue from third-party providers.  ### Base API URL  ``` http://localhost:8080/api/crm/v1 ```   # noqa: E501

    OpenAPI spec version: 0.3.0
    Contact: docs@supaglue.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.accounts_api import AccountsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_account(self):
        """Test case for create_account

        Create account  # noqa: E501
        """
        pass

    def test_get_account(self):
        """Test case for get_account

        Get account  # noqa: E501
        """
        pass

    def test_get_accounts(self):
        """Test case for get_accounts

        List accounts  # noqa: E501
        """
        pass

    def test_update_account(self):
        """Test case for update_account

        Update account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
