openapi: 3.0.3
info:
  version: 0.13.1
  title: Metadata API
  contact:
    name: Supaglue
    email: docs@supaglue.com
    url: 'https://supaglue.com'
  description: |
    #### Introduction

    Welcome to the Metadata API documentation for CRM. You can use this API to operate on metadata across multiple third-party providers.

    [![Run in Postman](https://run.pstmn.io/button.svg)](https://www.postman.com/supaglue/workspace/supaglue-public/overview)

    #### Base API URL
    ```
    https://api.supaglue.io/metadata/v2
    ```
  # externalDocs:
  #   description:
  #   url: 'https://www.postman.com/supaglue/workspace/supaglue-public/overview'
servers:
  - url: 'https://api.supaglue.io/metadata/v2'
    description: Supaglue API
paths:
  '/objects/custom':
    $ref: paths/objects@custom.yaml
  '/objects/standard':
    $ref: paths/objects@standard.yaml
  '/properties':
    $ref: paths/properties.yaml
tags:
  - name: StandardObjects
    description: A `Standard Object` is an object that is available by default in the provider.
  - name: Properties
    description: A `Property` is a field in a Provider Object.
components:
  securitySchemes:
    x-api-key:
      $ref: ../../common/components/securitySchemes/x-api-key.yaml
  schemas:
    property_deprecated:
      $ref: ./components/schemas/objects/property_deprecated.yaml
    standard_object:
      $ref: ./components/schemas/objects/standard_object.yaml
    simple_custom_object:
      $ref: ./components/schemas/objects/simple_custom_object.yaml
    object_type:
      $ref: ./components/schemas/objects/object_type.yaml
    object:
      $ref: ./components/schemas/objects/object.yaml
    errors:
      $ref: ../../common/components/schemas/errors.yaml
    warnings:
      $ref: ../../common/components/schemas/warnings.yaml
  parameters:
    x-customer-id:
      $ref: ../../common/components/parameters/header/x-customer-id.yaml
    x-provider-name:
      $ref: ../../common/components/parameters/header/x-provider-name.yaml
  responses:
    badRequest:
      $ref: ../../common/components/responses/badRequest.yaml
    conflict:
      $ref: ../../common/components/responses/conflict.yaml
    forbidden:
      $ref: ../../common/components/responses/forbidden.yaml
    internalServerError:
      $ref: ../../common/components/responses/internalServerError.yaml
    notFound:
      $ref: ../../common/components/responses/notFound.yaml
    notImplemented:
      $ref: ../../common/components/responses/notImplemented.yaml
    remoteProviderError:
      $ref: ../../common/components/responses/remoteProviderError.yaml
    unauthorized:
      $ref: ../../common/components/responses/unauthorized.yaml
    unprocessableEntity:
      $ref: ../../common/components/responses/unprocessableEntity.yaml
