type: object
properties:
  project_id:
    type: string
    example: my-project
  dataset:
    type: string
    example: my-dataset
  credentials:
    type: object
    properties:
      client_email:
        type: string
        example: supaglue@supaglue-382017.iam.gserviceaccount.com
      private_key:
        type: string
        example: -----BEGIN PRIVATE KEY-----\nMII...
    required:
      - client_email
required:
  - project_id
  - dataset
  - credentials
