type: object
properties:
  fields:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
          example: apolla_first_name
      required:
        - name
  allow_additional_field_mappings:
    type: boolean
required:
  - fields
  - allow_additional_field_mappings
