type: object
properties:
  host:
    type: string
    example: my-cluster.z31wcmj.mongodb.net
  database:
    type: string
    example: my-cluster
  user:
    type: string
    example: myuser
required:
  - host
  - database
  - user
