type: object
properties:
  host:
    type: string
    example: production-db-new.cluster-cdhnnutnlctj.us-west-2.rds.amazonaws.com
  port:
    type: number
    example: 5432
  database:
    type: string
    example: postgres_prod_db
  schema:
    type: string
    example: public
  user:
    type: string
    example: myuser
  ssl_mode:
    type: string
    enum:
      - disable
      - allow
      - prefer
      - require
    example: disable
  password:
    type: string
    example: mysensitivepassword
required:
  - host
  - port
  - database
  - schema
  - user
  - password
