type: object
properties:
  host:
    type: string
    example: production-db-new.cluster-cdhnnutnlctj.us-west-2.rds.amazonaws.com
  port:
    type: number
    example: 5432
  database:
    type: string
    example: postgres_prod_db
  schema:
    type: string
    example: public
  user:
    type: string
    example: myuser
  ssl_mode:
    type: string
    enum:
      - disable
      - no-verify
      - prefer
      - require
      - verify-ca
      - verify-full
    example: disable
  password:
    type: string
    example: mysensitivepassword
  server_ca_cert:
    type: string
    example: ---BEGIN CERTIFICATE-----
  client_cert:
    type: string
    example: ---BEGIN CERTIFICATE-----
  client_key:
    type: string
    example: ---BEGIN RSA PRIVATE KEY-----
  server_name:
    type: string
    example: 1-dd8643d8-f1ce-420f-a867-66b78a4734be.us-central1.sql.goog

required:
  - host
  - port
  - database
  - schema
  - user
  - password
