type: object
properties:
  region:
    type: string
    example: us-west-2
  bucket:
    type: string
    example: my-test-bucket
  access_key_id:
    type: string
    example: AKIAIOSFODNN7EXAMPLE
  secret_access_key:
    type: string
    example: A1lciPB09K2iqNHTLAftxTHy0SKGxNcO4QecAsZS
required:
  - region
  - bucket
  - access_key_id
  - secret_access_key
