type: object
properties:
  region:
    type: string
    example: us-west-2
  bucket:
    type: string
    example: my-test-bucket
  access_key_id:
    type: string
    example: AKIAIOSFODNN7EXAMPLE
required:
  - region
  - bucket
  - access_key_id
