type: object
properties:
  bucket:
    type: string
    example: s3://my-bucket-name
  region:
    type: string
    example: us-west-2
  access_key_id:
    type: string
    example: AKIDFIAKFISDKFSI
required:
  - bucket
  - region
  - access_key_id
