description: This is for field mappings when you data model using [Objects](https://docs.supaglue.com/platform/objects/overview#schemas). The field mappings here are set by your customers using the [Field Mappings API](https://docs.supaglue.com/api/v2/mgmt/update-object-field-mappings).
type: object
properties:
  common_objects:
    type: array
    items:
      type: object
      properties:
        object:
          type: string
          example: Contact__c
        field_mappings:
          type: array
          items:
            $ref: ./object_field_mapping.yaml
      required:
        - object
        - field_mappings
  standard_objects:
    type: array
    items:
      type: object
      properties:
        object:
          type: string
          example: Contact
        field_mappings:
          type: array
          items:
            $ref: ./object_field_mapping.yaml
      example:
      required:
        - object
        - field_mappings
