type: object
properties:
  id:
    type: string
    example: 465fdcb7-26b4-4090-894c-67cab41022bb
  application_id:
    type: string
    example: 9572d08b-f19f-48cc-a992-1eb7031d3f6a
  destination_name:
    type: string
    example: postgres
  provider_name:
    $ref: ./provider_name.yaml
  config:
    $ref: ./sync_config_data.yaml
required:
  - id
  - application_id
  - destination_name
  - provider_name
  - config
