type: object
description: An object that stores Oauth2/API key/access key related credentials.
properties:
  provider_app_id:
    type: string
  oauth:
    type: object
    properties:
      oauth_scopes:
        type: array
        items:
          type: string
      credentials:
        type: object
        properties:
          oauth_client_id:
            type: string
          oauth_client_secret:
            type: string
        required:
          - oauth_client_id
          - oauth_client_secret
    required:
      - oauth_scopes
      - credentials
required:
  - provider_app_id
  - oauth
example:
  provider_app_id: my_app_id
  oauth:
    oauth_scopes:
      - crm.objects.contacts.read
      - crm.objects.companies.read
      - crm.objects.deals.read
      - crm.objects.owners.read
      - crm.objects.contacts.write
      - crm.objects.companies.write
      - crm.objects.deals.write
    credentials:
      oauth_client_id: 7393b5a4-5e20-4648-87af-b7b297793fd1
      oauth_client_secret: 941b846a-5a8c-48b8-b0e1-41b6d4bc4f1a
