openapi: 3.1.0
info:
  version: 0.4.1
  title: Supaglue Management API
  contact:
    name: Supaglue
    email: docs@supaglue.com
    url: 'https://supaglue.com'
  description: |
    # Introduction

    Welcome to the Supaglue Management API documentation. You can use this API to manage customer integrations and connections.

    ### Base API URL

    ```
    http://localhost:8080/mgmt/v1
    ```
externalDocs:
  description: Try out our API in Postman!
  url: 'https://www.postman.com/supaglue/workspace/supaglue-public/overview'
servers:
  - url: 'http://localhost:8080/mgmt/v1'
    description: Local Supaglue API
paths:
  '/customers':
    $ref: paths/customers.yaml
  '/customers/{customer_id}':
    $ref: paths/customers@{customer_id}.yaml
  '/integrations':
    $ref: paths/integrations.yaml
  '/integrations/{integration_id}':
    $ref: paths/integrations@{integration_id}.yaml
  '/customers/{customer_id}/connections':
    $ref: paths/connections.yaml
  '/customers/{customer_id}/connections/{connection_id}':
    $ref: paths/connections@{connection_id}.yaml
  '/webhook':
    $ref: paths/webhook.yaml
tags: []
components:
  securitySchemes:
    ApiKeyAuth:
      $ref: ../common/components/securitySchemes/x-api-key.yaml
  schemas:
    customer:
      $ref: ./components/schemas/objects/customer.yaml
    integration:
      $ref: ./components/schemas/objects/integration.yaml
    connection:
      $ref: ./components/schemas/objects/connection.yaml
    category:
      $ref: ./components/schemas/objects/category.yaml
    integration_config:
      $ref: ./components/schemas/objects/integration_config.yaml
    provider_name:
      $ref: ./components/schemas/objects/provider_name.yaml
    create_update_customer:
      $ref: ./components/schemas/create_update_customer.yaml
    create_update_integration:
      $ref: ./components/schemas/create_update_integration.yaml
    webhook:
      $ref: ./components/schemas/objects/webhook.yaml
    webhook-payload:
      $ref: './components/schemas/webhook-payload.yaml'
webhooks:
  webhook:
    post:
      operationId: webhook
      summary: Webhook
      tags:
        - Webhook
      requestBody:
        content:
          application/json:
            schema:
              $ref: './components/schemas/webhook-payload.yaml'
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
