openapi: 3.0.3
info:
  version: 0.3.3
  title: Supaglue Management API
  contact:
    name: Supaglue
    email: docs@supaglue.com
    url: 'https://supaglue.com'
  description: |
    # Introduction

    Welcome to the Supaglue Management API documentation. You can use this API to manage customer integrations and connections.

    ### Base API URL

    ```
    http://localhost:8080/mgmt/v1
    ```
externalDocs:
  description: Try out our API in Postman!
  url: 'https://www.postman.com/supaglue/workspace/supaglue-public/overview'
servers:
  - url: 'http://localhost:8080/mgmt/v1'
    description: Local Supaglue API
paths:
  '/customers':
    $ref: paths/customers.yaml
  '/customers/{customer_id}':
    $ref: paths/customers@{customer_id}.yaml
  '/integrations':
    $ref: paths/integrations.yaml
  '/integrations/{integration_id}':
    $ref: paths/integrations@{integration_id}.yaml
  '/customers/{customer_id}/connections':
    $ref: paths/customers@{customer_id}connections.yaml
  '/customers/{customer_id}/connections/{connection_id}':
    $ref: paths/customers@{customer_id}connections@{connection_id}.yaml
tags: []
components:
  schemas:
    customer:
      $ref: ./components/schemas/objects/customer.yaml
    integration:
      $ref: ./components/schemas/objects/integration.yaml
    connection:
      $ref: ./components/schemas/objects/connection.yaml
    connection_credentials:
      $ref: ./components/schemas/objects/connection_credentials.yaml
    category:
      $ref: ./components/schemas/objects/category.yaml
    integration_config:
      $ref: ./components/schemas/objects/integration_config.yaml
    provider_name:
      $ref: ./components/schemas/objects/provider_name.yaml
    create_update_customer:
      $ref: ./components/schemas/create_update_customer.yaml
    create_update_integration:
      $ref: ./components/schemas/create_update_integration.yaml
