get:
  operationId: getApplications
  tags:
    - Applications
  security:
    - ApiKeyAuth: []
  summary: List applications
  description: >-
    Get a list of applications
  responses:
    '200':
      description: Applications
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../components/schemas/objects/application.yaml
          examples:
            Example:
              value:
                - application_id: your-applications-unique-application-id
                  name: My Staging App
                - application_id: your-other-applications-unique-application-id2
                  name: My Production App
post:
  operationId: createApplication
  summary: Create application
  tags:
    - Applications
  security:
    - ApiKeyAuth: []
  parameters: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            name:
              type: string
              example: My Production App
          required:
            - name
  responses:
    '201':
      description: Application created
      content:
        application/json:
          schema:
            $ref: ../components/schemas/objects/application.yaml
