post:
  operationId: createApplicationApiKey
  summary: Create application API key
  tags:
    - API key
  parameters: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
        examples:
          Example:
            value:
              api_key: cgx3ElGtCfucNrqqh11ymQ5yjeSD6KTpPShEUU9fWUbJXCoVHGhzTi7DIb5zcwcYDnWRouyBLLMnCT4CmYowVg==

  responses:
    '201':
      description: Application API key created
      content:
        application/json:
          schema:
            $ref: ../components/schemas/objects/application_api_key.yaml

parameters:
  - name: application_id
    in: path
    required: true
    schema:
      type: string
      example: 0623bf1c-3f71-4d53-ab11-f92ae72833c0
