post:
  operationId: deleteApplicationApiKey
  summary: Delete Application API key
  tags:
    - API key
  responses:
    200:
      description: API key
      content:
        application/json:
          schema:
            $ref: ../components/schemas/objects/application_api_key.yaml
          examples:
            Example:
              value:
                api_key: null

parameters:
  - name: application_id
    in: path
    required: true
    schema:
      type: string
      example: 0623bf1c-3f71-4d53-ab11-f92ae72833c0
