get:
  operationId: getApplication
  summary: Get application
  tags:
    - Applications
  responses:
    200:
      description: Application
      content:
        application/json:
          schema:
            $ref: ../components/schemas/objects/application.yaml
          examples:
            Example:
              value:
                id: e888cedf-e9d0-42c5-9485-2d72984faef4
                name: my-app
                config:
                  - webhook:
                      url: http://localhost:8080
                      request_type: POST
                      notify_on_sync_success: true
                      notify_on_sync_error: true
                      notify_on_connection_success: true
                      notify_on_connection_error: true
put:
  operationId: updateApplication
  summary: Update application
  tags:
    - Applications
  parameters: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../components/schemas/create_update_application.yaml
  responses:
    200:
      description: Application
      content:
        application/json:
          schema:
            $ref: ../components/schemas/objects/application.yaml
          examples:
            Example:
              value:
                id: 7fefba62-f90c-48f3-b44d-88298b68f831
                name: my-app
                config:
                  - webhook:
                      url: http://localhost:8080
                      request_type: POST
                      notify_on_sync_success: true
                      notify_on_sync_error: true
                      notify_on_connection_success: true
                      notify_on_connection_error: true
delete:
  operationId: deleteApplication
  summary: Delete application
  tags:
    - Applications
  responses:
    200:
      description: Application
      content:
        application/json:
          schema:
            $ref: ../components/schemas/objects/application.yaml
          examples:
            Example:
              value:
                id: 10072ab8-db4c-4e4f-9766-bbd846c9efbc
                name: my-app
                config:
                  - webhook:
                      url: http://localhost:8080
                      request_type: POST
                      notify_on_sync_success: true
                      notify_on_sync_error: true
                      notify_on_connection_success: true
                      notify_on_connection_error: true
parameters:
  - name: application_id
    in: path
    required: true
    schema:
      type: string
      example: 0623bf1c-3f71-4d53-ab11-f92ae72833c0
