type: object
properties:
  default_config:
    type: object
    properties:
      period_ms:
        type: integer
        minimum: 60000
        example: 60000
      strategy:
        type: string
        enum:
          - full then incremental
          - full only
    required:
      - period_ms
      - strategy
  common_objects:
    type: array
    items:
      type: object
      properties:
        object:
          type: string
          example: contacts
      required:
        - object
  standard_objects:
    type: array
    items:
      type: object
      properties:
        object:
          type: string
          example: contacts
      required:
        - object
  custom_objects:
    type: array
    items:
      type: object
      properties:
        object:
          type: string
          example: contacts
      required:
        - object
required:
  - default_config
example:
  default_config:
    period_ms: 60000
    strategy: full then incremental
