type: object
properties:
  destination_config:
    description: An object to override the default Destination configuration per connection.
    oneOf:
      - description: Config specific to Postgres destination
        type: object
        title: Postgres
        properties:
          type:
            type: string
            enum: [postgres]
          schema:
            type: string
            description: The schema you'd like to sync to. This schema must already exist. Supaglue will not create it. If not specified, the schema specified in the Postgres Destination will be used.
            example: customer_1_schema
        required:
          - type
          - schema
      - description: Config specific to BigQuery destination
        type: object
        title: BigQuery
        properties:
          type:
            type: string
            enum: [bigquery]
          dataset:
            type: string
            description: The dataset you'd like to sync to. This dataset must already exist. Supaglue will not create it. If not specified, the dataset specified in the BigQuery Destination will be used.
            example: customer_1_dataset
        required:
          - type
          - dataset
  standard_objects:
    description: A list of case-sensitive Provider standard objects to by synced. If specified, this list will take override the custom_objects list in SyncConfig.
    type: array
    items:
      oneOf:
        - type: object
          title: All
          properties:
            object:
              type: string
              description: The Provider object name (case sensitive)
              example: Contact
          required:
            - object
        - type: object
          title: Postgres/BigQuery (Preview)
          properties:
            object:
              type: string
              description: The Provider object name (case sensitive)
              example: Contact
            table:
              type: string
              description: The table to write the object to. If specified, this will override the default table used by Supaglue.
              example: my_contacts
          required:
            - object
            - table
  custom_objects:
    description: |
      (Preview) A list of case-sensitive Provider custom objects to be synced. If specified, this list will take override the custom_objects list in SyncConfig.
    type: array
    items:
      oneOf:
        - type: object
          title: All
          properties:
            object:
              type: string
              description: The Provider object name (case sensitive)
              example: Contact__c
          required:
            - object
        - type: object
          title: Postgres/BigQuery (Preview)
          properties:
            object:
              type: string
              description: The Provider object name (case sensitive)
              example: Contact__c
            table:
              type: string
              description: The table to write the object to. If specified, this will override the default table used by Supaglue.
              example: my_contacts
          required:
            - object
            - table
