/*
 * Supaglue Management API
 * # Introduction  Welcome to the Supaglue Management API documentation. You can use this API to manage customer integrations and connections.  ### Base API URL  ``` http://localhost:8080/mgmt/v1 ``` 
 *
 * OpenAPI spec version: 0.3.3
 * Contact: docs@supaglue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Application;
import io.swagger.client.model.CreateUpdateApplication;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ApplicationsApi
 */
@Ignore
public class ApplicationsApiTest {

    private final ApplicationsApi api = new ApplicationsApi();

    /**
     * Create application
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createApplicationTest() throws Exception {
        CreateUpdateApplication body = null;
        Application response = api.createApplication(body);

        // TODO: test validations
    }
    /**
     * Delete application
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteApplicationTest() throws Exception {
        String applicationId = null;
        Application response = api.deleteApplication(applicationId);

        // TODO: test validations
    }
    /**
     * Get application
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getApplicationTest() throws Exception {
        String applicationId = null;
        Application response = api.getApplication(applicationId);

        // TODO: test validations
    }
    /**
     * List applications
     *
     * Get a list of applications
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getApplicationsTest() throws Exception {
        List<Application> response = api.getApplications();

        // TODO: test validations
    }
    /**
     * Update application
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateApplicationTest() throws Exception {
        CreateUpdateApplication body = null;
        String applicationId = null;
        Application response = api.updateApplication(body, applicationId);

        // TODO: test validations
    }
}
