/*
 * Supaglue Customer API
 * # Introduction  Welcome to the Supaglue Management API documentation. You can use this API to manage customer integrations and connections.  ### Base API URL  ``` http://localhost:8080/mgmt/v1 ``` 
 *
 * OpenAPI spec version: 0.3.3
 * Contact: docs@supaglue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Connection;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ConnectionsApi
 */
@Ignore
public class ConnectionsApiTest {

    private final ConnectionsApi api = new ConnectionsApi();

    /**
     * Delete connection
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteConnectionTest() throws Exception {
        String customerId = null;
        String connectionId = null;
        Connection response = api.deleteConnection(customerId, connectionId);

        // TODO: test validations
    }
    /**
     * Get connection
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getConnectionTest() throws Exception {
        String customerId = null;
        String connectionId = null;
        Connection response = api.getConnection(customerId, connectionId);

        // TODO: test validations
    }
    /**
     * List connections
     *
     * Get a list of connections
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getConnectionsTest() throws Exception {
        String customerId = null;
        List<Connection> response = api.getConnections(customerId);

        // TODO: test validations
    }
}
