# NOTE: Using 3.1.0 because we want to document webhooks.
# Other than the `webhooks` key, we should not use 3.1.0 features since the validation middleware doesn't support it yet
openapi: 3.1.0
info:
  version: 0.7.3
  title: Supaglue Management API
  contact:
    name: Supaglue
    email: docs@supaglue.com
    url: 'https://supaglue.com'
  description: |
    # Introduction

    Welcome to the Supaglue Management API documentation. You can use this API to manage customer integrations and connections.

    ### Base API URL

    ```
    http://localhost:8080/mgmt/v1
    ```
externalDocs:
  description: Try out our API in Postman!
  url: 'https://www.postman.com/supaglue/workspace/supaglue-public/overview'
servers:
  - url: 'http://localhost:8080/mgmt/v1'
    description: Local Supaglue API
paths:
  '/customers':
    $ref: paths/customers.yaml
  '/customers/{customer_id}':
    $ref: paths/customers@{customer_id}.yaml
  '/integrations':
    $ref: paths/integrations.yaml
  '/integrations/{integration_id}':
    $ref: paths/integrations@{integration_id}.yaml
  '/customers/{customer_id}/connections':
    $ref: paths/connections.yaml
  '/customers/{customer_id}/connections/{connection_id}':
    $ref: paths/connections@{connection_id}.yaml
  '/webhook':
    $ref: paths/webhook.yaml
  '/sync-history':
    $ref: paths/sync_history.yaml
  '/sync-info':
    $ref: paths/sync_info.yaml
tags: []
components:
  securitySchemes:
    ApiKeyAuth:
      $ref: ../common/components/securitySchemes/x-api-key.yaml
  schemas:
    customer:
      $ref: ./components/schemas/objects/customer.yaml
    integration:
      $ref: ./components/schemas/objects/integration.yaml
    connection:
      $ref: ./components/schemas/objects/connection.yaml
    category:
      $ref: ./components/schemas/objects/category.yaml
    integration_config:
      $ref: ./components/schemas/objects/integration_config.yaml
    provider_name:
      $ref: ./components/schemas/objects/provider_name.yaml
    create_update_customer:
      $ref: ./components/schemas/create_update_customer.yaml
    create_update_integration:
      $ref: ./components/schemas/create_update_integration.yaml
    webhook:
      $ref: ./components/schemas/objects/webhook.yaml
    sync_info:
      $ref: ./components/schemas/sync_info.yaml
    sync_history:
      $ref: ./components/schemas/sync_history.yaml
    webhook-payload:
      $ref: './components/schemas/webhook-payload.yaml'
  parameters:
    cursor:
      $ref: ../common/components/parameters/query/cursor.yaml
    page_size:
      $ref: ../common/components/parameters/query/page_size.yaml
    customer_id:
      $ref: ../common/components/parameters/query/customer_id.yaml
    provider_name:
      $ref: ../common/components/parameters/query/provider_name.yaml
webhooks:
  webhook:
    $ref: ./webhooks/webhook.yaml
