type: object
properties:
  default_config:
    type: object
    properties:
      period_ms:
        type: integer
        minimum: 60000
        example: 60000
      strategy:
        type: string
        enum:
          - full then incremental
          - full only
    required:
      - period_ms
      - strategy
  common_objects:
    type: array
    items:
      type: object
      properties:
        object:
          type: string
          example: contacts
        fetch_all_fields_into_raw:
          type: boolean
        config_override:
          type: object
          properties:
            period_ms:
              type: integer
              minimum: 60000
              example: 60000
            strategy:
              type: string
              enum:
                - full then incremental
                - full only
      required:
        - object
        - fetch_all_fields_into_raw
  raw_objects:
    type: array
    items:
      type: object
      properties:
        object:
          type: string
          example: contacts
        config_override:
          type: object
          properties:
            period_ms:
              type: integer
              minimum: 60000
              example: 60000
            strategy:
              type: string
              enum:
                - full then incremental
                - full only
      required:
        - object
required:
  - default_config
  - common_objects
  - raw_objects
example:
  default_config:
    period_ms: 60000
    strategy: full then incremental
