type: object
properties:
  host:
    type: string
    example: https://mydb.com
  port:
    type: number
    example: 5432
  database:
    type: string
    example: my_database
  schema: 
    type: string
    example: public
  user:
    type: string
    example: myuser
  password:
    type: string
    example: password
required:
  - host
  - port
  - database
  - schema
  - user
  - password
