openapi: 3.0.3
info:
  version: 0.3.0
  title: Supaglue Customer API
  contact:
    name: Supaglue
    email: docs@supaglue.com
    url: 'https://supaglue.com'
  description: |
    # Introduction

    Welcome to the Supaglue unified CRM API documentation. You can use this API to read data that has been synced into Supaglue from third-party providers.

    ### Base API URL

    ```
    http://localhost:8080/api/customer/v1
    ```
externalDocs:
  description: Try out our API in Postman!
  url: 'https://www.postman.com/supaglue/workspace/supaglue-public/overview'
servers:
  - url: 'https://localhost:8080/customer/v1'
    description: Local Supaglue API
paths:
  '/customers/{customer_id}/integrations/{integration_id}/connections/{connection_id}/sync-info':
    $ref: paths/customers@{customer_id}@integrations@{integration_id}@connections@{connection_id}@sync-info.yaml
  '/customers/{customer_id}/integrations/{integration_id}/connections/{connection_id}/sync-history':
    $ref: paths/customers@{customer_id}@integrations@{integration_id}@connections@{connection_id}@sync-history.yaml
tags:
  - name: Sync
    description: Provides metadata about `Syncs`.
components:
  schemas:
    logs:
      $ref: ../common/components/schemas/logs.yaml
    errors:
      $ref: ../common/components/schemas/errors.yaml
    warnings:
      $ref: ../common/components/schemas/warnings.yaml
    pagination:
      $ref: ../common/components/schemas/pagination.yaml
  # TODO: uncomment when we implement API authentication
  # securitySchemes:
  #   api_key:
  #     type: apiKey
  #     name: X-Account-Token
  #     in: header
  #     description: Token identifying the end user
  parameters:
    created_after:
      $ref: ../common/components/parameters/created_after.yaml
    created_before:
      $ref: ../common/components/parameters/created_before.yaml
    updated_after:
      $ref: ../common/components/parameters/updated_after.yaml
    updated_before:
      $ref: ../common/components/parameters/updated_before.yaml
    cursor:
      $ref: ../common/components/parameters/cursor.yaml
    expand:
      $ref: ../common/components/parameters/expand.yaml
    page_size:
      $ref: ../common/components/parameters/page_size.yaml
    connection_id:
      $ref: ./components/parameters/connection_id.yaml
    integration_id:
      $ref: ./components/parameters/integration_id.yaml
    customer_id:
      $ref: ./components/parameters/customer_id.yaml
