import LogsTable from '@/components/logs/LogsTable';
import { useSyncHistory } from '@/hooks/useSyncHistory';
import Header from '@/layout/Header';
import { getServerSideProps } from '@/pages';
import { Box } from '@mui/material';
import Head from 'next/head';
import { useState } from 'react';

export { getServerSideProps };

export default function Home() {
  const { syncHistories } = useSyncHistory();
  const [mobileOpen, setMobileOpen] = useState(false);

  const handleDrawerToggle = () => {
    setMobileOpen(!mobileOpen);
  };

  return (
    <>
      <Head>
        <title>Supaglue Management Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
        <Header title="Sync Logs" onDrawerToggle={handleDrawerToggle} />
        <Box component="main" sx={{ flex: 1, py: 6, px: 4, bgcolor: '#eaeff1' }}>
          <LogsTable data={syncHistories?.results ?? []} />
        </Box>
      </Box>
    </>
  );
}
