/*
 * Supaglue API
 * # Introduction  Welcome to the Supaglue unified CRM API documentation. You can use this API to read data that has been synced into Supaglue from third-party providers.  ### Base API URL  ``` http://localhost:8080/api/crm/v1 ``` 
 *
 * OpenAPI spec version: 0.3.0
 * Contact: docs@supaglue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Contact;
import io.swagger.client.model.ContactsBody;
import io.swagger.client.model.ContactsContactIdBody;
import io.swagger.client.model.InlineResponse2001;
import io.swagger.client.model.InlineResponse2011;
import org.threeten.bp.OffsetDateTime;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ContactsApi
 */
@Ignore
public class ContactsApiTest {

    private final ContactsApi api = new ContactsApi();

    /**
     * Create contact
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createContactTest() throws Exception {
        ContactsBody body = null;
        InlineResponse2011 response = api.createContact(body);

        // TODO: test validations
    }
    /**
     * Get contact
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getContactTest() throws Exception {
        String contactId = null;
        String expand = null;
        Contact response = api.getContact(contactId, expand);

        // TODO: test validations
    }
    /**
     * List contacts
     *
     * Get a list of contacts
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getContactsTest() throws Exception {
        OffsetDateTime createdAfter = null;
        OffsetDateTime createdBefore = null;
        OffsetDateTime updatedAfter = null;
        OffsetDateTime updatedBefore = null;
        String cursor = null;
        String expand = null;
        String pageSize = null;
        InlineResponse2001 response = api.getContacts(createdAfter, createdBefore, updatedAfter, updatedBefore, cursor, expand, pageSize);

        // TODO: test validations
    }
    /**
     * Update contact
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateContactTest() throws Exception {
        ContactsContactIdBody body = null;
        String contactId = null;
        InlineResponse2011 response = api.updateContact(body, contactId);

        // TODO: test validations
    }
}
