# coding: utf-8

"""
    Supaglue CRM API

    # Introduction  Welcome to the Supaglue unified CRM API documentation. You can use this API to read data that has been synced into Supaglue from third-party providers.  ### Base API URL  ``` http://localhost:8080/crm/v1 ```   # noqa: E501

    OpenAPI spec version: 0.4.1
    Contact: docs@supaglue.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class PassthroughApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def send_passthrough_request(self, body, x_customer_id, x_provider_name, **kwargs):  # noqa: E501
        """Send passthrough request  # noqa: E501

        Send request directly to a provider  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.send_passthrough_request(body, x_customer_id, x_provider_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PassthroughBody body: (required)
        :param str x_customer_id: The customer ID (required)
        :param str x_provider_name: The provider name (required)
        :return: InlineResponse2005
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.send_passthrough_request_with_http_info(body, x_customer_id, x_provider_name, **kwargs)  # noqa: E501
        else:
            (data) = self.send_passthrough_request_with_http_info(body, x_customer_id, x_provider_name, **kwargs)  # noqa: E501
            return data

    def send_passthrough_request_with_http_info(self, body, x_customer_id, x_provider_name, **kwargs):  # noqa: E501
        """Send passthrough request  # noqa: E501

        Send request directly to a provider  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.send_passthrough_request_with_http_info(body, x_customer_id, x_provider_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PassthroughBody body: (required)
        :param str x_customer_id: The customer ID (required)
        :param str x_provider_name: The provider name (required)
        :return: InlineResponse2005
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'x_customer_id', 'x_provider_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method send_passthrough_request" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `send_passthrough_request`")  # noqa: E501
        # verify the required parameter 'x_customer_id' is set
        if ('x_customer_id' not in params or
                params['x_customer_id'] is None):
            raise ValueError("Missing the required parameter `x_customer_id` when calling `send_passthrough_request`")  # noqa: E501
        # verify the required parameter 'x_provider_name' is set
        if ('x_provider_name' not in params or
                params['x_provider_name'] is None):
            raise ValueError("Missing the required parameter `x_provider_name` when calling `send_passthrough_request`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'x_customer_id' in params:
            header_params['x-customer-id'] = params['x_customer_id']  # noqa: E501
        if 'x_provider_name' in params:
            header_params['x-provider-name'] = params['x_provider_name']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/passthrough', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2005',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
