# coding: utf-8

"""
    Supaglue Management API

    # Introduction  Welcome to the Supaglue Management API documentation. You can use this API to manage customer integrations and connections.  ### Base API URL  ``` http://localhost:8080/mgmt/v1 ```   # noqa: E501

    OpenAPI spec version: 0.6.0
    Contact: docs@supaglue.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class SyncApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_sync_history(self, **kwargs):  # noqa: E501
        """Get Sync History  # noqa: E501

        Get a list of Sync History objects.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_sync_history(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object cursor: The pagination cursor value
        :param object page_size: Number of results to return per page
        :param object customer_id: The customer ID that uniquely identifies the customer in your application
        :param object provider_name: The provider name
        :param object model: The model name to filter by
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_sync_history_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_sync_history_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_sync_history_with_http_info(self, **kwargs):  # noqa: E501
        """Get Sync History  # noqa: E501

        Get a list of Sync History objects.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_sync_history_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object cursor: The pagination cursor value
        :param object page_size: Number of results to return per page
        :param object customer_id: The customer ID that uniquely identifies the customer in your application
        :param object provider_name: The provider name
        :param object model: The model name to filter by
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['cursor', 'page_size', 'customer_id', 'provider_name', 'model']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_sync_history" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'cursor' in params:
            query_params.append(('cursor', params['cursor']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501
        if 'customer_id' in params:
            query_params.append(('customer_id', params['customer_id']))  # noqa: E501
        if 'provider_name' in params:
            query_params.append(('provider_name', params['provider_name']))  # noqa: E501
        if 'model' in params:
            query_params.append(('model', params['model']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth']  # noqa: E501

        return self.api_client.call_api(
            '/sync-history', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_sync_infos(self, **kwargs):  # noqa: E501
        """Get Sync Info  # noqa: E501

        Get a list of Sync Info  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_sync_infos(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object customer_id: The customer ID that uniquely identifies the customer in your application
        :param object provider_name: The provider name
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_sync_infos_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_sync_infos_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_sync_infos_with_http_info(self, **kwargs):  # noqa: E501
        """Get Sync Info  # noqa: E501

        Get a list of Sync Info  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_sync_infos_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object customer_id: The customer ID that uniquely identifies the customer in your application
        :param object provider_name: The provider name
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['customer_id', 'provider_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_sync_infos" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'customer_id' in params:
            query_params.append(('customer_id', params['customer_id']))  # noqa: E501
        if 'provider_name' in params:
            query_params.append(('provider_name', params['provider_name']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth']  # noqa: E501

        return self.api_client.call_api(
            '/sync-info', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
