FROM node:18-bullseye-slim AS base

FROM base AS builder
WORKDIR /workspace
RUN yarn global add turbo
COPY . .
RUN --mount=type=cache,mode=0777,target=/workspace/.yarn/cache,id=api-yarn-cache turbo prune --scope=api --docker

# Add lockfile and package.json's of isolated subworkspace
FROM base AS dev
WORKDIR /workspace

# First install dependencies (as they change less often)
COPY . .
COPY .yarnrc.build.yml .yarnrc.yml
COPY .yarn .yarn
COPY --from=builder /workspace/out/json/ .
COPY --from=builder /workspace/out/yarn.lock ./yarn.lock
RUN --mount=type=cache,mode=0777,target=/workspace/.yarn/cache,id=api-yarn-cache yarn install
