name: CI

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Enable yarn
        if: env.ACT
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Lint changed workspaces
        if: github.ref != 'refs/heads/main'
        run: yarn lint "--filter=[origin/main...HEAD]"

      - name: Lint
        if: github.ref == 'refs/heads/main'
        run: yarn lint

      - name: Build changed workspaces
        if: github.ref != 'refs/heads/main'
        # don't waste time building mgmt-ui and docs since vercel does it for us
        run: yarn build "--filter=...[origin/main...HEAD]" --filter=!mgmt-ui --filter=!docs

      - name: Build
        if: github.ref == 'refs/heads/main'
        run: yarn build

      - name: Test changed workspaces
        if: github.ref != 'refs/heads/main'
        run: yarn test "--filter=...[origin/main...HEAD]"

      - name: Test
        if: github.ref == 'refs/heads/main'
        run: yarn test
