name: Build and Push Docker image

on:
  workflow_call:
    inputs:
      workspace:
        description: workspace to deploy
        required: true
        type: string
      image-name:
        description: image name to create
        required: true
        type: string
      build-args:
        description: arguments to pass to docker build
        required: false
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        description: Docker Hub username
        required: true
      DOCKERHUB_TOKEN:
        description: Docker Hub token
        required: true
      STAGING_KUBECONFIG:
        description: Kubeconfig for staging cluster
        required: true
      build-args:
        description: arguments to pass to docker build
        required: false

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    name: Build and Push to Docker Hub
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: corepack enable

      - name: Docker meta
        if: '!env.ACT'
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ github.token }}
          # list of Docker images to use as base name for tags
          images: |
            supaglue/${{ inputs.image-name }}
          tags: |
            type=ref,event=branch,prefix=branch-,enable=${{ github.ref != 'refs/heads/main' }}
            type=edge,branch=main
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Set up Depot CLI
        if: '!env.ACT'
        uses: depot/setup-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: '!env.ACT'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get directory of yarn workspace
        id: get-directory
        run: |
          echo "directory=$(yarn workspaces list --json | jq -r 'select( .name == "${{ inputs.workspace }}") | .location')" >> $GITHUB_ENV

      - name: Build and push
        uses: depot/build-push-action@v1
        with:
          project: 2bljgst1rr
          context: .
          file: ./${{ env.directory }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' && !env.ACT }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ${{ inputs.build-args }}
            ${{ secrets.build-args }}

  deploy:
    name: Deploy to staging
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::146006058524:role/deployer-role
          role-session-name: GitHub_Deploy
          aws-region: us-west-2

      - name: Set kubeconfig
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.STAGING_KUBECONFIG }}

      - uses: azure/setup-kubectl@v3
        id: kubectl
        with:
          version: v1.25.10

      - name: Deploy
        run: |
          ${{ steps.kubectl.outputs.kubectl-path }} rollout restart deployment -n supaglue supaglue-${{ inputs.workspace }}
          ${{ steps.kubectl.outputs.kubectl-path }} rollout status deployment -n supaglue supaglue-${{ inputs.workspace }}
          ${{ steps.kubectl.outputs.kubectl-path }} exec deploy/supaglue-api -n supaglue -- sh -c "npx prisma@4.12.0 migrate deploy && node node_modules/@supaglue/db/prisma/seed.js"
