name: Build and push Salesforce Pub/Sub Docker image

on:
  workflow_dispatch:
  push:
    paths:
      - apps/salesforce-pub-sub/**
      - packages/core/**
      - packages/db/**
      - packages/schemas/**
      - packages/types/**
      - packages/utils/**
    branches:
      - '**'
  pull_request:
    paths:
      - apps/salesforce-pub-sub/**
      - packages/core/**
      - packages/db/**
      - packages/schemas/**
      - packages/types/**
      - packages/utils/**

concurrency:
  group: ${{ github.repository }}-salesforce-pub-sub-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build_and_push:
    name: Build and push Docker image
    uses: ./.github/workflows/docker_build_and_push.yml
    with:
      workspace: salesforce-pub-sub
      image-name: salesforce-pub-sub
    secrets:
      build-args: |
        POSTHOG_API_KEY=${{ secrets.POSTHOG_API_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      STAGING_KUBECONFIG: ${{ secrets.STAGING_KUBECONFIG }}
