name: Build and push sync-worker Docker image

on:
  workflow_dispatch:
  push:
    paths:
      - apps/sync-worker/**
      - packages/core/**
      - packages/db/**
      - packages/sync-workflows/**
      - packages/types/**
      - packages/utils/**
    branches:
      - main
  pull_request:
    paths:
      - apps/sync-worker/**
      - packages/core/**
      - packages/db/**
      - packages/sync-workflows/**
      - packages/types/**
      - packages/utils/**

concurrency:
  group: ${{ github.repository }}-sync_worker-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build_and_push:
    name: Build and push Docker image
    uses: ./.github/workflows/docker_build_and_push.yml
    if: github.event_name == 'push'
    with:
      workspace: sync-worker
      image-name: sync-worker
      depot-project: fh1fxkkb69
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      STAGING_KUBECONFIG: ${{ secrets.STAGING_KUBECONFIG }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
