# coding: utf-8

"""
    Supaglue Management API

    # Introduction  Welcome to the Supaglue Management API documentation. You can use this API to manage customer integrations and connections.  ### Base API URL  ``` http://localhost:8080/mgmt/v1 ```   # noqa: E501

    OpenAPI spec version: 0.3.3
    Contact: docs@supaglue.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.applications_api import ApplicationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestApplicationsApi(unittest.TestCase):
    """ApplicationsApi unit test stubs"""

    def setUp(self):
        self.api = ApplicationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_application(self):
        """Test case for create_application

        Create application  # noqa: E501
        """
        pass

    def test_delete_application(self):
        """Test case for delete_application

        Delete application  # noqa: E501
        """
        pass

    def test_get_application(self):
        """Test case for get_application

        Get application  # noqa: E501
        """
        pass

    def test_get_applications(self):
        """Test case for get_applications

        List applications  # noqa: E501
        """
        pass

    def test_update_application(self):
        """Test case for update_application

        Update application  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
