# coding: utf-8

"""
    Supaglue Customer API

    # Introduction  Welcome to the Supaglue Management API documentation. You can use this API to manage customer integrations and connections.  ### Base API URL  ``` http://localhost:8080/mgmt/v1 ```   # noqa: E501

    OpenAPI spec version: 0.3.3
    Contact: docs@supaglue.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.provider_name import ProviderName  # noqa: E501
from swagger_client.rest import ApiException


class TestProviderName(unittest.TestCase):
    """ProviderName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProviderName(self):
        """Test ProviderName"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.provider_name.ProviderName()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
