# coding: utf-8

"""
    Supaglue Customer API

    # Introduction  Welcome to the Supaglue Management API documentation. You can use this API to manage customer integrations and connections.  ### Base API URL  ``` http://localhost:8080/mgmt/v1 ```   # noqa: E501

    OpenAPI spec version: 0.3.3
    Contact: docs@supaglue.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.customers_api import CustomersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomersApi(unittest.TestCase):
    """CustomersApi unit test stubs"""

    def setUp(self):
        self.api = CustomersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_customer(self):
        """Test case for create_customer

        Create customer  # noqa: E501
        """
        pass

    def test_delete_customer(self):
        """Test case for delete_customer

        Delete customer  # noqa: E501
        """
        pass

    def test_get_customer(self):
        """Test case for get_customer

        Get customer  # noqa: E501
        """
        pass

    def test_get_customers(self):
        """Test case for get_customers

        List customers  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
